### ISSUE TITLE
发布包里包含log4j配置文件，会覆盖别人的log4j配置文件

### ISSUE THREAD

**Issue by gaoxjin** [CrawlScript/WebCollector#104]

**Comment by hujunxianligong** [comment]
貌似会优先选择你的配置文件吧？

gaoxjin <notifications@github.com> 于2019年3月16日周六 下午4:52写道：

**Comment by gaoxjin** [comment]
java -cp ./lib/*;./conf;这种方式运行，会优先第三方jar里的配置文件

**Comment by gaoxjin** [comment]
经测试，确实./conf要放在./lib前面才能覆盖第三方jar里的配置文件
