### ISSUE TITLE
自动识别新闻时间部分存在BUG

### ISSUE THREAD

**Issue by KTsama** [CrawlScript/WebCollector#127]
Class : cn.edu.hfut.dmic.contentextractor.ContentExtractor
Line : 201
正则：([1-2][0-9]{3})[^0-9]{1,5}?([0-1]?[0-9])[^0-9]{1,5}?([0-9]{1,2})[^0-9]{1,5}?([0-2]?[1-9])[^0-9]{1,5}?([0-9]{1,2})[^0-9]{1,5}?([0-9]{1,2})
匹配目标：2021-02-18 00:39:00 会匹配失败
原因：([1-2][0-9]{3})[^0-9]{1,5}?([0-1]?[0-9])[^0-9]{1,5}?([0-9]{1,2})[^0-9]{1,5}?([0-2]? ---【[1-9]】--- )[^0-9]{1,5}?([0-9]{1,2})[^0-9]{1,5}?([0-9]{1,2})
应更改为：([1-2][0-9]{3})[^0-9]{1,5}?([0-1]?[0-9])[^0-9]{1,5}?([0-9]{1,2})[^0-9]{1,5}?([0-2]?[0-9])[^0-9]{1,5}?([0-9]{1,2})[^0-9]{1,5}?([0-9]{1,2})

**Comment by hujunxianligong** [comment]
感谢！
我回头看修复一下。
