### ISSUE TITLE
ContentCollector解析时间的正则表达式bug

### ISSUE THREAD

**Issue by 52Jolynn** [CrawlScript/WebCollector#21]
源码中getTime，getDate方法中提供的解析时间的正则表达式可以匹配2015ab08cd20mn这样的字符串，为何不使用更为严格的正则呢？如：
([1-9](?:[0-9]{3}|[0-9]))[-/年](1[0-2]|0?[1-9])[-/月]([12][0-9]|3[01]|0?[1-9])日?[\\s|&nbsp;]*(?:(1[0-9]|2[0-3]|0?[0-9])[:时]([1-5][0-9]|0?[0-9])[:分]?(?:([1-5][0-9]|0?[0-9])秒?)?(?:\\.[0-9]{3})?)?

**Comment by hujunxianligong** [comment]
谢谢，后期考虑不用正则，算法在改进中。
