### ISSUE TITLE
webCollector中的新版本ContentExtractor是否可以单独使用

### ISSUE THREAD

**Issue by w821881341** [CrawlScript/WebCollector#28]
webCollector中的新版本ContentExtractor是否可以单独使用

**Comment by hujunxianligong** [comment]
可以

Owen <notifications@github.com>于2016年1月17日周日 下午5:13写道：

**Comment by w821881341** [comment]
有单独的jar包吗或者需要自己单独打包？

**Comment by hujunxianligong** [comment]
导入Webcollector所有jar就行

Owen <notifications@github.com>于2016年1月17日周日 下午5:15写道：

**Comment by w821881341** [comment]
那样岂不是很繁冗~我试试单独抽取吧

**Comment by hujunxianligong** [comment]
为什么会冗余，jar包才3M，而且又不会因为jar包中的其他东西而影响效率。

Owen <notifications@github.com>于2016年1月17日周日 下午5:18写道：
