### ISSUE TITLE
visitt抛异常了， 我不希望再爬，怎么做？

### ISSUE THREAD

**Issue by ostarsier** [CrawlScript/WebCollector#29]
Page page = getPage(crawlDatum);     
       crawlDatum.incrRetry(page.getRetry());
                    crawlDatum.setFetchTime(System.currentTimeMillis());

                    CrawlDatums next = new CrawlDatums();
                    if (visit(crawlDatum, page, next)) {
                        try {
                            /*写入fetch信息*/
                            dbManager.wrtieFetchSegment(crawlDatum);

我看你的retry是在getPage里，获取页面我没有报错，我是在visit里报错的，所以没有
dbManager.wrtieFetchSegment(crawlDatum);，也没有retry+1，还是没有爬的状态，所以一直在跑？是这样吗？

**Comment by hujunxianligong** [comment]
如果visit出现异常，作为爬虫框架，应该重新爬取。
对于开发者，这里应该自己捕捉异常，捕捉到需要忽略的异常，用catch处理掉即可。
