### ISSUE TITLE
教程列表的地址一个也打不开

### ISSUE THREAD

**Issue by zbcdj2008** [CrawlScript/WebCollector#32]
是我的原因还是服务挂了
+ [JAVA爬虫WebCollector 2.x入门教程——基本概念](http://datahref.com/book/article.php?article=webcollector_2x_intro)
+ [WebCollector教程——在Eclipse项目中配置使用WebCollector爬虫](http://datahref.com/book/article.php?article=wc_tutor_eclipse)
+ [WebCollector教程——爬取搜索引擎](http://datahref.com/book/article.php?article=webcollector_BingSearch)
+ [WebCollector教程——爬取新浪微博](http://datahref.com/book/article.php?article=webcollector_WeiboCrawler)
+ [WebCollector教程——获取当前深度](http://datahref.com/book/article.php?article=webcollector_DepthCrawler)
+ [WebCollector设置代理](http://datahref.com/book/article.php?article=webcollector_proxy)
+ [WebCollector网页正文提取](http://datahref.com/book/article.php?article=webcollector_content_extraction)
+ [WebCollector爬取JS加载的数据](http://datahref.com/book/article.php?article=webcollector_selenium)
+ [WebCollector分布式爬取](http://datahref.com/book/article.php?article=webcollector_hadoop_intro)
+ [Lazy爬虫配置教程](http://datahref.com/book/article.php?article=lazy_config)
![qq 20160129180258](https://cloud.githubusercontent.com/assets/1982308/12672651/9b561c64-c6b2-11e5-8254-8eccb1c722aa.png)

**Comment by hujunxianligong** [comment]
服务器已修复

zbcdj2008 <notifications@github.com>于2016年1月29日周五 下午6:03写道：

**Comment by zbcdj2008** [comment]
@hujunxianligong 又挂掉了，另外发现一个问题，github的教程链接和oschina上面的教程链接地址是不一样的
http://www.oschina.net/p/webcollector
这上面的教程链接都是短的，我去网站看了，可以看到标题，无法打开内容。只有首页是正常的。
![qq 20160203111631](https://cloud.githubusercontent.com/assets/1982308/12771875/a2804c18-ca67-11e5-8c9a-98ba03b32871.png)

**Comment by hujunxianligong** [comment]
sorry，服务器内存太小，后面考虑升级一下。。。

zbcdj2008 <notifications@github.com>于2016年2月3日周三 上午11:17写道：

**Comment by hujunxianligong** [comment]
非常抱歉，教程已全部迁移到CSDN，教程列表可在http://www.oschina.net/p/webcollector上查看
