### ISSUE TITLE
最新版的有在重定向时set cookie吗？

### ISSUE THREAD

**Issue by zemochen** [CrawlScript/WebCollector#35]
我用的不是最新版的，最近遇到重定向逻辑问题，场景如下：
模拟登陆，自动获取授权码，目标网页登陆（简称：A）后会重定向到用户首页（简称：B），同事给一个set-cookie的请求头，重定向到B时，如果没有把set-cookie中的cookie放入到“Cookie”中，就会造成一直反复重定向。

所以我在httpRequest.getResponse()中加入如下代码：

```
String newCookie = con.getHeaderField("Set-Cookie");
if (StringUtils.isNotBlank(newCookie)) {
      this.setCookie(newCookie);
      response.addHeader("Cookie", newCookie);
      this.crawlDatum.putMetaData("Cookie", newCookie);
}
```

这样就避免登陆成功因为没有setCookie导致重定向后又重定向会登陆页面的死循环，同时可以在后面的crawl中继续使用这个Cookie,知道新的“set-cookie”出现。
如果需要的话我可以吧重写的httpRequest给你你review一下，或者我push到我的fork中.

**Comment by hujunxianligong** [comment]
复杂http请求请参考教程：http://blog.csdn.net/AJAXHu/article/details/50699500
