### ISSUE TITLE
深度爬取，存储berkeleydb错误，爬取完成不释放内存

### ISSUE THREAD

**Issue by 123yxp123** [CrawlScript/WebCollector#43]
使用样例：
\WebCollector-master\WebCollector\src\main\java\cn\edu\hfut\dmic\webcollector\example\DemoDepthCrawler.java
存储错误，爬取完成不是否内存，导致内存溢出。导致系统cup 内存使用率高，信息如下：
云盘：http://pan.baidu.com/s/1nvpk9Vb
密码：mnqz
请求解答。

**Comment by Rayn-liuwei** [comment]
我也遇到这个问题了。。。。使用的  cn.edu.hfut.dmic.webcollector.plugin.berkeley.BerkeleyDBManager 。。楼主最后解决了吗？？

**Comment by hujunxianligong** [comment]
现在上了RocksDB内核了
