### ISSUE TITLE
java.lang.NoClassDefFoundError: org/openqa/selenium/htmlunit/HtmlUnitDriver

### ISSUE THREAD

**Issue by huangwenyan1225** [CrawlScript/WebCollector#44]
爬取javascript报这个错

**Comment by huangwenyan1225** [comment]
开发工具用idea  用maven导入

**Comment by hujunxianligong** [comment]
请到selenium社区咨询，该组件不由本项目进行维护，谢谢!

**Comment by Jack-fd** [comment]
<dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-htmlunit-driver</artifactId>
            <version>2.52.0</version>
        </dependency>

**Comment by Mr-Malone** [comment]
这个错误是因为依赖的版本错误，
