### ISSUE TITLE
WebCollector 2.31 选择器（select bug）

### ISSUE THREAD

**Issue by stoneJava** [CrawlScript/WebCollector#45]
在使用新版的2.31版从日本气象厅网站抓取台风数据时，select 方法会有丢失情况，
网址地址：http://www.jma.go.jp/en/typh/index.html
抓取内容：地图右边的台风信息，table 内容
抓取代码如下：
Elements forecast = doc.getElementsByClass("forecast").select("tr");
forecast 中获取的 tr 有丢失情况发生

**Comment by hujunxianligong** [comment]
这是你自己业务代码的问题

**Comment by stoneJava** [comment]
就这么点代码，没有任何业务，我抓取所有的tr，forecast的数量和实际tr的数量长度不一致，而且同样代码2.09版就没发现这样的问题。

**Comment by hujunxianligong** [comment]
CSS选择器内置的是JSOUP，你要考虑几个问题
1）是否每次网页的源码规律都一样
2）自己编写的CSS选择器是否足够稳定，能够适应页面的变化
3）如果真出了问题，请前往JSOUP项目提交BUG。

2016-08-08 11:16 GMT+08:00 stoneJava <notifications@github.com>:

**Comment by stoneJava** [comment]
抓取缺少tr时，我分析了网页源代码，是没有发生变化的，可能真是jsoup的BUG，谢谢你耐心的解答。

**Comment by stoneJava** [comment]
WebCollector 2.31 中使用的是JSOUP-1.83版本，把依赖换成最新的JSOUP-1.92，问题解决。
