### ISSUE TITLE
爬取的页面内部链接能修改么

### ISSUE THREAD

**Issue by zbcdj2008** [CrawlScript/WebCollector#52]
比如我爬取的网站到本地后，html页面内部的链接怎么修改为本地链接，绝对路径修改为本地相对路径，这个问题很常见的吧

**Comment by shenchenyang** [comment]
no

**Comment by SweetInk** [comment]
使用jsoup找到你需要修改的a标签，修改Element的attribute。
在visit方法中拿到Document
eg：
`
  Document doc = page.doc();
  String path="your localpath";
  doc.select("a").attr("href","localpath");//
//TODO 保存本地或者其他操作
`
