### ISSUE TITLE
如何在visited方法中把拼接的url放入到url队列中？

### ISSUE THREAD

**Issue by wuxiongliu1** [CrawlScript/WebCollector#60]
在visited中，如何将拼接的url放入到待处理队列中呢？
调用crawlDatums.add() 方法可以将url加入到队列中，但是发现在处理这个页面的时候，不会自动收集该页面中的所有链接了；
autoParse已经设置为了true了；

**Comment by hujunxianligong** [comment]
你可以看一下那些链接是不是真的在HTML中，还是由JS加载的
