### ISSUE TITLE
能否添加多个正则规则呢？

### ISSUE THREAD

**Issue by wuxiongliu1** [CrawlScript/WebCollector#61]
您好，在使用您的框架的时候，首先默认设置autoParse=true,这样可以把符合正则规则的url全部添加进来；
然后在处理这样的url的时候，拼接出具体的api 请求url，虽然使用CrawlDatums add 进去，但是这些添加的url是不生效的，因为不符合这个原先设定的url规则；所以想问一下，可不可以设置多个url的正则规则？

**Comment by hujunxianligong** [comment]
你手工添加进去的URL不会被过滤的。正则是用来探测URL，不是用来过滤URL的。
