### ISSUE TITLE
jar包缺少问题

### ISSUE THREAD

**Issue by ljc930611** [CrawlScript/WebCollector#63]
爬取Javascript加载的数据引入
<dependency>
	<groupId>org.seleniumhq.selenium</groupId>
	<artifactId>selenium-java</artifactId>
	<version>2.44.0</version>
</dependency>
在实例化对象时:
HtmlUnitDriver driver = new HtmlUnitDriver();
报缺少jar包：Exception in thread "Thread-40" java.lang.NoClassDefFoundError: com/gargoylesoftware/htmlunit/javascript/host/Event
这个是我需要引入com.gargoylesoftware.htmlunit这个jar包吗？我在网上没有找到这个maven的包。能方便给我个下载地址吗

**Comment by liutUway** [comment]
都是通过mava自动下载的。

不过我用的phantomjs，这个扫描出来的内容多一些。            





liut@uway.cn
 
发件人： ljc930611
发送时间： 2017-07-17 09:53
收件人： CrawlScript/WebCollector
抄送： Subscribed
主题： [CrawlScript/WebCollector] jar包缺少问题 (#63)
爬取Javascript加载的数据引入

org.seleniumhq.selenium
selenium-java
2.44.0

在实例化对象时:
HtmlUnitDriver driver = new HtmlUnitDriver();
报缺少jar包：Exception in thread "Thread-40" java.lang.NoClassDefFoundError: com/gargoylesoftware/htmlunit/javascript/host/Event
这个是我需要引入com.gargoylesoftware.htmlunit这个jar包吗？我在网上没有找到这个maven的包。能方便给我个下载地址吗

**Comment by ljc930611** [comment]
你好，问一下：
@Override
    public void visit(Page page, CrawlDatums next) {
        System.out.println("visiting:"+page.getUrl()+"\tdepth="+page.meta("depth"));
    }
这个page里面的方法好像都过时了，是不是现在不推荐了，现在应该使用什么样的

**Comment by ljc930611** [comment]
呃。看错了

**Comment by ljc930611** [comment]
问一下，爬取Javascript加载的数据还能通过正则捕捉所需要的url吗。如果可以请问需要怎么写，因为HtmlUnitDriver中没有addRegex方法
