### ISSUE TITLE
CrawlDatums next中添加后续任务的问题

### ISSUE THREAD

**Issue by ljc930611** [CrawlScript/WebCollector#64]
next.add("http://nba.win007.com"+url).meta("matchSeason",params.get("matchSeason")).meta("SclassID",params.get("SclassID"));
我在next中添加了URL参数但是发现并没有执行，是因为深度的问题吗？crawler.start(1);因为我的深度为1，所以并不会查询后续的任务吗？
但是当我将深度改为2的时候报错org.json.JSONObject.keySet()Ljava/util/Set;不知道是什么原因

**Comment by ljc930611** [comment]
您好，问一下：
1、现在BreadthCrawler中没有setProxy方法了请问怎么设置代理？
2、addRegex中只想获取某一个class下的url应该怎么写？

**Comment by hujunxianligong** [comment]
1）添加到next之后会在后续的depth中抓取。
2）简单设置代理：http://datahref.com/archives/17
3）高级设置代理： 自定义Requester插件

**Comment by wang1784594241** [comment]
经常使用的应该是列表、详情、下一页列表、详情 这样，应该说这种的深度是2，只有列表和详情。

  现在有个问题用next添加当前页解析的下一页，则深度为2就取不到添加的下一页数据，必须提前把深度设置的大一些，如果分页不确定有多少页，深度就会设置的过大或过小。

  有没有方法可以在列表页添加与自己同深度的nextPage列表页呢，就是种子的类型是type 为list的列表第一页，在type list的page中处理时需要同时设置下一页和本页的详情页并且深度2可以都解析到。或者有没有在处理page时动态添加种子的方法。

**Comment by djxhero** [comment]
next.add 不能即 add(抓取 下一页列表)   有 add(文章内容)。感觉抓取下一页 这个机制考虑不周全。必须预先指定好抓取多少也吗？

**Comment by hujunxianligong** [comment]
add返回的是当前所有的next，andAndReturn返回的才是当前的
