### ISSUE TITLE
爬取给定url的所有子页面，子子页面

### ISSUE THREAD

**Issue by yaoyuanyy** [CrawlScript/WebCollector#67]
楼主，练习webcollector过程中，我遇到一个问题：我的需求是爬取给定url的所有子页面，子子页面，初始page为this.addSeed("http://www.163.com/");

public AutoNewsCrawler(String crawlPath, boolean autoParse) { super(crawlPath, autoParse); /start page/ this.addSeed("http://www.163.com/");

    /*fetch url like http://news.hfut.edu.cn/show-xxxxxxhtml*/
    this.addRegex("https://www.163.com/.*");

    setThreads(50);
    getConf().setTopN(100);
// setResumable(true); }

@加贝 public void visit(Page page, CrawlDatums next) { String url = page.url(); /if page is news page/ if (page.matchUrl("http://www.163.com/.*")) {

        /*extract title and content of news by css selector*/
        String me = page.regex("四川九寨沟7.0级地震");
        String title = page.select("div[id=Article]>h2").first().text();
         
        System.out.println("me:" + me);
        System.out.println("title:\n" + title);
        
    }
}
我重写的AutoNewsCrawler如上述代码，问题为：我运行后，抓取不到http://www.163.com/的子页面信息，看官方文档说明，子页面是从开始页面一步一步得到的，但是我debug没有找到子页面，难道page.matchUrl("http://www.163.com/.*"一定要加上尾部，如page.matchUrl("http://www.163.com/tt.*"这样的吗，我不确定，请教你

**Comment by hujunxianligong** [comment]
你的autopare设置为true了么？

**Comment by hujunxianligong** [comment]
具体使用问题请加群探讨，ISSUE主要是用来交流源码BUG的

**Comment by yaoyuanyy** [comment]
申请加群了，没通过呢
