### ISSUE TITLE
有没有集群方案和demo？单机单线程测试爬取速度不理想

### ISSUE THREAD

**Issue by Janus-Xu** [CrawlScript/WebCollector#68]
测试一个线程，半小时爬10000;
另部署分布式集群，后续对接flume、hadoop这些的简便方案有么

**Comment by hujunxianligong** [comment]
请问你为啥不开50个线程。。。。

**Comment by shitao0713** [comment]
单线程爬能不慢才奇怪

**Comment by Janus-Xu** [comment]
我可以开多线程，讲单机单线程只是为了方便计算需要多少机器开多少线程才能在合理时间内完成任务。
另外分布式集群方案到底有没有，还是没有给出回复，关注三个点：一是自动分派任务到爬虫集群，二是爬虫集群状态的监控，三是后续持久化的对接

**Comment by Mr-Malone** [comment]
这个问题恐怕还没解决方案，
