### ISSUE TITLE
2.70版本HttpRequest中的setUserAgent()方法无效

### ISSUE THREAD

**Issue by yanzuo1992** [CrawlScript/WebCollector#72]
在执行setUserAgent()时，会执行setHeader()
但是setHeader()并不会更新this.userAgent
在2.70版本HttpRequest的response()中会执行
if (this.userAgent != null) {
            this.setUserAgent(this.userAgent);
        }
因为this.userAgent为默认值，且setUserAgent又没有更新此值 导致设置的UA不生效

**Comment by yxssfxwzy** [comment]
好像是有这个问题

**Comment by Mr-Malone** [comment]
这个怎么解决呢？

**Comment by Mr-Malone** [comment]
我设置了setUserAgent()
然而我执行了getUserAgent()的方法，但是返回的并不是我设置的UserAgent()；

**Comment by hbslover** [comment]
确实无效的哦. 只能重写这个方法

**Comment by hbslover** [comment]
@Override
	public void setUserAgent(String userAgent) {
		this.userAgent = userAgent;
		setHeader("User-Agent", this.userAgent);
	}

**Comment by hujunxianligong** [comment]
不好意思，老版本的Bug，新版本现在修复了。
