### ISSUE TITLE
多个爬虫同时爬取

### ISSUE THREAD

**Issue by ljc930611** [CrawlScript/WebCollector#74]
我现在有两个爬虫，其中一个由于网站限制，在里面使用了Thread.sleep(),导致这个爬虫没有运行结束，另一个爬虫则不会运行。。。怎么才能使另一个爬虫开始启动？

**Comment by ljc930611** [comment]
为什么 crawler.start(2);这个不是异步执行的，难道一定要这个爬虫爬取结束另外的爬虫才能启动吗

**Comment by hujunxianligong** [comment]
你不能自己写两个线程分别运行两个爬虫么。。。。

ljc930611 <notifications@github.com> 于 2017年11月2日周四 上午11:53写道：

**Comment by ljc930611** [comment]
我两个代码不在一个线程里面，一个定时器爬取新闻是每分钟爬取一次，另一个定时器是每天固定几个点去另一个网站同步数据，但是同步数据所需的时间比较长，导致了在我同步数据的时候没有去爬取新闻。现在我的处理情况是自己去做线程池和网络请求把同步数据的那部分不使用webCollector，不知道怎么使用webCollector解决这样的问题

**Comment by yxssfxwzy** [comment]
写两个程序可以吗？两个程序同时执行

**Comment by zhoubinghong159261** [comment]
有没有爬过国际在线新闻，你如果爬会了国际在线新闻你就懂了！！！
