### ISSUE TITLE
关于IP代理的问题

### ISSUE THREAD

**Issue by zhangzhengk** [CrawlScript/WebCollector#81]
IP注入的时候怎么时时的监控失效的IP进行清除，目前好像只是一次注入

**Comment by hujunxianligong** [comment]
能否提供具体一点的问题？

**Comment by zhangzhengk** [comment]
另外不知道有没有关于使用代理的例子，网上的资料都比较少，想加群但是提示人满了加不进去。菜鸟目前还只会模仿着写

**Comment by hujunxianligong** [comment]
参考首页中多代理的例子：
https://github.com/CrawlScript/WebCollector
