### ISSUE TITLE
注入URL，只执行一部分

### ISSUE THREAD

**Issue by Mr-Malone** [CrawlScript/WebCollector#85]
我注入的URL有19个，但还是他只爬取了6个，而且程序也没有报错。说明一下，URL是不同的，而且是强制注入，如果你知道的话请指导我一下。因为是爬取的动态加载的数据，我使用的phantomjs。

**Comment by hujunxianligong** [comment]
请给出具体的代码，谢谢

**Comment by Mr-Malone** [comment]
我检查了程序，发现是phantomjs的问题。
针对新版本的框架API有吗？我找到的教程，大部分都是老版本的，而且您的QQ群也加不进去，一直是在摸索中使用，心中有许多困惑。

**Comment by hujunxianligong** [comment]
留个QQ号吧

**Comment by Mr-Malone** [comment]
958258458
