### ISSUE TITLE
官网配置教程中的NewsCrawler.java报错

### ISSUE THREAD

**Issue by MrKingHH** [CrawlScript/WebCollector#86]
## 用的是本地java项目导包的方式 
**已经从github上下载了最新的jar包，类名字也保持一致，但是还是报错。Page类没有getDoc()和getUrl()方法，还有crawler.setTopN(100)出错。**  师兄有时间帮忙看一下。

**Comment by hujunxianligong** [comment]
请参考首页README.md的最新教程
https://github.com/CrawlScript/WebCollector
