### ISSUE TITLE
StrategyCrawler类的stop方法能否立即停止爬虫行为

### ISSUE THREAD

**Issue by BeQiang** [CrawlScript/WebCollector#88]
实现思路：
我再爬虫类定义了一个实例变量
private volatile Integer insertCount = 3;
在visit方法中判断insertCount是否==0，如果不等于0则进行爬取工作否则调用stop方法。
如果爬取到了目标数据则insertCount --；
    /**
     * 停止爬虫
     */
    public void stop() {
        status = STOPED;
        fetcher.stop();
    }
这个方法在visit方法中调用并不能停止爬虫。我的测试代码爬取的数据量很小(就十几条)，我想实现只爬取指定数量的记录就自动停止爬虫行为。

**Comment by hujunxianligong** [comment]
不过不经过等待，强行停止这些正在运行的线程是有风险的。
如果真的有需要，自己加个强关吧。
