### ISSUE TITLE
重定向

### ISSUE THREAD

**Issue by YYSpace** [CrawlScript/WebCollector#90]
我需要爬取一个需要登陆的网页，账号与密码我也有了，但是page.code=302,无法重定向到我需要的网址中

**Comment by hujunxianligong** [comment]
1. 对于重定向，参考首页DEMO中几个redirect例子
2. 对于登录，检车一下是不是其他的原因

**Comment by YYSpace** [comment]
![image](https://user-images.githubusercontent.com/24581506/44315591-60a05e00-a458-11e8-955a-7805b25c03ac.png)
![image](https://user-images.githubusercontent.com/24581506/44315601-76ae1e80-a458-11e8-9097-f2be3f717e5c.png)
我使用的版本是：2.71

**Comment by hujunxianligong** [comment]
请升级至2.73

**Comment by InuYasha000** [comment]
重定向后发现并没有跳转到我想要的页面，比如是某个网站菜单下的具体某个菜单页，但是确实网站的主页
